# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    ports:
      - 99:80
    volumes:
      - ./src:/var/www/html
    restart: always
    tty: true
    stdin_open: true
